---
title: "R Notebook"
output: html_notebook
---


```{r}
seurobj <- readRDS('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/data/10x-180831')
```



```{r fig1, fig.height=15, fig.width=10, fig.align="center"}
VlnPlot(seurobj, c("nGene", "percent.mito", "nUMI"), group.by='timepoint', nCol = 1, point.size.use=-1)
```

```{r}
GenePlot(seurobj, 'nUMI', 'nGene', cex.use = 0.5)
```


```{r}
PCElbowPlot(seurobj) #15 pcs
```

```{r}
PCAPlot(seurobj, group.by='timepoint', pt.size=0.1)
```

```{r}
TSNEPlot(seurobj, group.by='timepoint', pt.size=0.1)
```

```{r}
TSNEPlot(seurobj, group.by='Phase', pt.size=0.1)
```

```{r}
FeaturePlot(seurobj, features.plot = 'nUMI', cols.use=c('grey', 'blue'), no.legend=F)
```

```{r}
FeaturePlot(seurobj, features.plot = 'percent.mito', cols.use=c('grey', 'blue'), no.legend = F)
```

```{r}
FeaturePlot(seurobj, features.plot = 'nGene', cols.use=c('grey', 'blue'), no.legend = F)
```


```{r}
FeaturePlot(seurobj, features.plot = 'EBF2', cols.use=c('grey', 'blue'), no.legend = F)
```

```{r}
FeaturePlot(seurobj, features.plot = 'TM4SF1', cols.use=c('grey', 'blue'), no.legend = F)
```

```{r}
FeaturePlot(seurobj, features.plot = 'LY6K', cols.use=c('grey', 'blue'), no.legend = F)
```

```{r}
FeaturePlot(seurobj, features.plot = 'PDGFRA', cols.use=c('grey', 'blue'), no.legend = F)
```

```{r}
TSNEPlot(seurobj, group.by='res.0.5', pt.size=0.1)
```

```{r}
TSNEPlot(seurobj, group.by='timepoint', pt.size=0.1)
```

```{r}

```

