---
title: "R Notebook"
output: html_notebook
---

How much singlets per sample and per donor? How much doublets?

```{r}

#function: read in file, filter filer file by barcodes. Print nr of singlets, nr of doublets, nr of ambiguous, nr of 
print_demuxlet_info <- function(folder_name, sample){
  demuxlet <- read.table(paste('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/data/demuxlet/demuxlet_out/', folder_name, '/180831_10x_', sample, '_demuxlet.best', sep=''), header=T, sep='\t')
  barcodes <- read.table(paste('/data/sc-10x/data-runs/171120-scheele-adipose/180831_10x_', sample,  '/outs/filtered_gene_bc_matrices/hg19/barcodes.tsv', sep=''))
  demuxlet_filtered <- demuxlet[which(demuxlet$BARCODE %in% barcodes$V1),]
  
  singlets <- as.vector(demuxlet_filtered$BEST[unlist(lapply(as.vector(demuxlet_filtered$BEST),function(x){return(startsWith(x, 'SNG'))}))])
  doublets <- as.vector(demuxlet_filtered$BEST[unlist(lapply(as.vector(demuxlet_filtered$BEST),function(x){return(startsWith(x, 'DBL'))}))])
  ambiguous <- as.vector(demuxlet_filtered$BEST[unlist(lapply(as.vector(demuxlet_filtered$BEST),function(x){return(startsWith(x, 'AMB'))}))])
  
  print(paste('Nr. of singlets: ', length(singlets), sep=''))
  print(paste('Nr. of doublets: ', length(doublets), sep=''))
  print(paste('Nr. of ambiguous: ', length(ambiguous), sep=''))
  print(paste('Avg N.SNP: ', mean(demuxlet_filtered$N.SNP), sep=''))
  
}
```

```{r}
list.dirs(path = "/projects/pytrik/sc_adipose/analyze_10x_fluidigm/data/demuxlet/demuxlet_out/", full.names=F)
```


```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_ger0.01', 's1')
```


```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_ger0.001', 's1')
```

```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_ger0.05', 's1')
```

```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_correct-refalleles_ger0.01', 's1')
```

```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_correct-refalleles_ger0.05', 's1')
```

```{r}
print_demuxlet_info('plink_bed-updated_vcf_sorted_header_correct-refalleles_ger0.001', 's1')
```


```{r}
print_demuxlet_info('chr1_22_combined.qc_r2_maf.vcf.recode_sorted_header', 's1')
```


```{r}
#print_demuxlet_info('demuxlet_out_ger0.001', 's1')
```

```{r}
print_demuxlet_info('demuxlet_out_ger0.05', 's1')
```


```{r}
print_demuxlet_info('chr1_22_combined.qc_r2_maf.vcf.recode_sorted_header', 's1')
```

```{r}
print_demuxlet_info('vcf_tutorial_gt', 's1')
```

```{r}
print_demuxlet_info('plink_bed-updated_sorted_header', 's1')
```

