---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(Seurat)
library(scmap)
library(SingleCellExperiment)
```


Data loading and inspection of the metadata.

```{r}
load('/data/pub-others/tabula_muris/figshare/180126-facs/maca.seurat_obj.facs.figshare_180126.RData')
head(seurat_obj@meta.data)
```


```{r}
unique(seurat_obj@meta.data$tissue_cell_type)
```

```{r}
sce_maca <- as.SingleCellExperiment(seurat_obj)
all10x <- readRDS('/projects/pytrik/sc_adipose/analyze_10x_fluidigm/data/10x')
sce_10x <- as.SingleCellExperiment(all10x)

#convert maca gene names to uppercase to match 10x gene names
rowData(sce_maca)['feature_symbol'] <- unlist(lapply(rowData(sce_maca)$gene, function(x){return(toupper(x))}))
rowData(sce_10x)['feature_symbol'] <- rowData(sce_10x)$gene

counts(sce_10x) <- as.matrix(counts(sce_10x))
logcounts(sce_10x) <- as.matrix(logcounts(sce_10x))
#sce_10x <- selectFeatures(sce_10x, suppress_plot = FALSE)
#sce_10x <- indexCluster(sce_10x, cluster_col = 'sample')

counts(sce_maca) <- as.matrix(counts(sce_maca))
logcounts(sce_maca) <- as.matrix(logcounts(sce_maca))
sce_maca <- selectFeatures(sce_maca, suppress_plot = FALSE)
sce_maca <- indexCluster(sce_maca, cluster_col = 'tissue_cell_type')
```


```{r}
library(pheatmap)
pheatmap(metadata(sce_maca)$scmap_cluster_index, show_rownames = FALSE)
```

```{r}
scmapCluster_results <- scmapCluster(
  projection = sce_10x, 
  index_list = list(
    sce_maca = metadata(sce_maca)$scmap_cluster_index
  ),
  threshold=0.5  #default=0.7 but doesn't give a lot of results
)

#TODO: predict subtissues

table(scmapCluster_results$scmap_cluster_labs)
```


```{r}
sce_maca <- indexCluster(sce_maca, cluster_col = 'subtissue')

scmapCluster_results_subtissue <- scmapCluster(
  projection = sce_10x, 
  index_list = list(
    sce_maca = metadata(sce_maca)$scmap_cluster_index
  ),
  threshold=0.5  #default=0.7 but doesn't give a lot of results
)
```


Mapping to clusters

```{r}
plot(
  getSankey(
    colData(sce_10x)$res.0.5, 
    scmapCluster_results$scmap_cluster_labs[,"sce_maca"],
    plot_height = 400
  )
)

#link: http://yggdrasil:7000/custom/googleVis/SankeyIDc04f191e7330.html

```

Annotations for cluster 12

```{r}
table(scmapCluster_results$scmap_cluster_labs[which(colData(sce_10x)$res.0.5 %in% 12),'sce_maca'])
```

Annotations for all

```{r}
table(scmapCluster_results$scmap_cluster_labs)
```


Mapping to subtissues

```{r}
plot(
  getSankey(
    colData(sce_10x)$sample_name, 
    scmapCluster_results$scmap_cluster_labs[,"sce_maca"],
    plot_height = 400
  )
)

#link: http://yggdrasil:7000/custom/googleVis/SankeyIDc04f6d50d5c.html
```


```{r}
plot(
  getSankey(
    colData(sce_10x)$sample_name, 
    scmapCluster_results_subtissue$scmap_cluster_labs[,"sce_maca"],
    plot_height = 400
  )
)
#link: http://yggdrasil:7000/custom/googleVis/SankeyIDc04f3f8dad9c.html
```


```{r}
predicted_labels <- as.data.frame(
    row.names=rownames(sce_10x@colData), 
    x=as.vector(scmapCluster_results$scmap_cluster_labs))
names(predicted_labels) <- 'predicted_labels'
all10x <- AddMetaData(all10x, metadata=predicted_labels, col.name='predicted_labels')
```

```{r}
TSNEPlot(all10x, group.by='sample_name', pt.size=0.1, do.label=T)
```

```{r}
TSNEPlot(all10x, group.by='predicted_labels', pt.size=0.1, do.label=T)
```

```{r}
#only cluster 12
#TSNEPlot(SubsetData(SetAllIdent(all10x, id = 'res.0.5'), ident.use = 12), group.by='predicted_labels', pt.size=0.1, do.label=T)
```


```{r}
#saveRDS(all10x, '/projects/pytrik/sc_adipose/analyze_10x_fluidigm/data/10x')
```

